### ISSUE TITLE
track1.txt output

### ISSUE THREAD

**Issue by danb31** [NVIDIAAICITYCHALLENGE/2018AICITY_ISU-TH#1]
Hi,

What is the format of the track1.txt output file? On my own dataset I get the following result:

1 1 0 1392 433 1554 512 53.25 0
1 2 0 1404 433 1567 511 52.95 0
1 3 0 1407 434 1566 512 53.13 0
1 4 0 1417 433 1577 509 52.63 0
...

What does each column represent?

Thanks!
Dan

**Comment by jane212** [comment]
Please see the track 1 evaluation metric on the challenge website. https://www.aicitychallenge.org/2018-data-sets/
